### ISSUE TITLE
[Suggestion] Consider sticking to RegisterEventHotKey instead of global event monitor

### ISSUE THREAD

**Issue by mstarke** [georgesnow/MacPassRevealer#7]
Using a global event monitor enables the plugin to capture all key events. Using a RegisterEventHotKey callback allows for the system to handle the callback and only get notified without having the need to read all key strokes.

AFAIK there are no plans to remove this Carbon API. Not every piece of Carbon is going to be deprecated soon, which seems to be a common misconception.

**Comment by georgesnow** [comment]
Ok - I noticed that it capture all events when I when I was testing, which seemed concerning to me cause carbon seemed much more thorough in handling global events with the os. And yes didn’t realize carbon wasn’t fully deprecated.I will switch it back.

**Comment by georgesnow** [comment]
@mstarke - returned it back to carbon API
